name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: update Meson
      run: python3 -m pip install meson -U
    - name: Configure with Meson
      run: meson . build
    - name: Build (meson)
      run: ninja -C build
    - name: Run tests (meson)
      run: ninja test -C build

  clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: update Meson
      run: python3 -m pip install meson -U
    - name: Configure with Meson
      run: CC=clang CXX=clang++ meson . build
    - name: Build (meson)
      run: ninja -C build
    - name: Run tests (meson)
      run: ninja test -C build

